import type { Metadata } from "next";
import "./globals.css";

import localfont from "next/font/local";
import { ThemeProvider } from "@/components/theme-provider";
import Wrapper from "@/components/Wrapper";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import CommandBox from "@/components/CommandBox";
import { Toaster } from "@/components/ui/sonner";

const biotif = localfont({
  src: [
    {
      path: "static/font/Biotif-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/static/font/Biotif-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-biotif",
});

const neuzeit = localfont({
  src: [
    {
      path: "static/font/NeuzeitGrotesk-bold.woff2",
      weight: "900",
      style: "Bold",
    },
  ],
  variable: "--font-neuzeit",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${biotif.variable} ${neuzeit.variable} font-biotif antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <div className="flex flex-col min-h-screen relative">
            <CommandBox>
              <Navbar />
              <Wrapper>{children}</Wrapper>
              <Footer />
            </CommandBox>
          </div>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
